os:
  - linux
  - osx

language: go

go:
    - 1.5.2

env:
    - GO15VENDOREXPERIMENT=1

install: true

script:
  - make deps
  - go test ./...

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false