blank_issues_enabled: false
contact_links:
  - name: Getting Help on IPFS
    url: https://ipfs.tech/help
    about: All information about how and where to get help on IPFS.
  - name: IPFS Discussion Forum
    url: https://discuss.ipfs.tech
    about: Please post general questions, support requests, and discussions here.
  - name: libp2p Discussion Forum
    url: https://discuss.libp2p.io
    about: Please post libp2p-specific questions and discussions here.
